---
logging:
  level:
    com.example: INFO
some:
  name: INFO
spring:
  jpa:
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/movies?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password:
